### ISSUE TITLE
SpringCollab Beginner Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#15]
```
- level: SpringCollab2020/1-Beginner
  maps:
    - sid: 'SpringCollab2020/1-Beginner/Abby'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Bissy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/CANADIAN'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Cat_in_Box_01'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Cookie'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Cruor'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/DanTKO'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Flagpole1up'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Ghajestis'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/hennyburgr'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/iamdadbod'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/IsaGoodFriend'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/itsabrody'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Lichtbaulb'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Rue'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Skeleton'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Snas'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/Thegur90'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/1-Beginner/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
