### ISSUE TITLE
Spring Collab Intermediate Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#16]
```
- level: SpringCollab2020/2-Intermediate
  maps:
    - sid: 'SpringCollab2020/2-Intermediate/aleph_null'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/aridai'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Bissy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Bonicle'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Clover'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Donker19'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Evilleafy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/GG19'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Goat'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Hallow'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/hennyburgr'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/iamdadbod'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Lichtbaulb'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Noax'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Oppen_Heimer'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/phant'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/ProXas'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Rocketguy2'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/SilverStar'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Skeleton'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/TheAdvertisement'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/Thegur90'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/2-Intermediate/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
