### ISSUE TITLE
Spring Collab Advanced Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#17]
```
- level: SpringCollab2020/3-Advanced
  maps:
    - sid: 'SpringCollab2020/3-Advanced/_sleepie'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/BeefyUncle'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Bissy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Cookie'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Dozing'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Ezel'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Galaksyz'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Holly'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/iamdadbod'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/JaThePlayer'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/LinjKarma'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/NeoKat'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/orbittwz'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Percussive'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/RealVet'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Rufus'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Spoopy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/taco360'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Thegur90'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/Tortoise'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/3-Advanced/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
