### ISSUE TITLE
Spring Collab Expert Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#18]
```
- level: SpringCollab2020/4-Expert
  maps:
    - sid: 'SpringCollab2020/4-Expert/Bissy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/CANADIAN'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/ChaotiC'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/dahlukeh'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/DeathKontrol'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/deskilln'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/iamdadbod'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Indecx'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Kube'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/LethargicDoggo'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Mineman'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Mun'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/RadleyMcTuneston'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Thegur90'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/Zerex'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/4-Expert/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
