### ISSUE TITLE
Spring Collab Grandmaster Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#19]
```
- level: SpringCollab2020/5-Grandmaster
  maps:
    - sid: 'SpringCollab2020/5-Grandmaster/1nkFa1c0n'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/Bissy'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/BobDole'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/CANADIAN'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/Cyber'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/DeathKontrol'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/dog'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/fishtank_overflow'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/Hydro0'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/iamdadbod'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/Problemstrol'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/TheDavSmasher'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/Thegur90'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
    - sid: 'SpringCollab2020/5-Grandmaster/ZZ-NewHeartSide'
      name:
        en: ''
      sides: [0]
```
