### ISSUE TITLE
Strawberry Jam Beginner Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#4]

**Comment by niuez** [comment]
```
- level: StrawberryJam2021/1-Beginner
  maps:
    - sid: 'StrawberryJam2021/1-Beginner/asteriskblue'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Bing_Over_Google'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/cellularAutomaton'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Ceph'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Circumplex'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/coffe'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/CoupCritik'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Eclipse'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Flagpole1up'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/frozenflygone'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/HankyMueller'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/hyperlife'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Jadeturtle'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/joltik'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/mosscairn'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/NotYourBadeline'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Owen-Shirrell'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/Quinnigan'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/skeleton'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/snas'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/voliver9'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/1-Beginner/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
