### ISSUE TITLE
Strawberry Jam Intermediate Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#5]

**Comment by niuez** [comment]
```
- level: StrawberryJam2021/2-Intermediate
  maps:
    - sid: 'StrawberryJam2021/2-Intermediate/Arphimigon'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/bryse0n'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Dooshii'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Emik'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Evilleafy'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Ezel'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/GlowWoomii'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Ice'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Jems'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/LegS'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Liero'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Luma'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/marlin'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/pixelator'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/Rocketguy2'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/SpoopySoup'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/thebreadstick1'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/vitellary'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/2-Intermediate/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
