### ISSUE TITLE
Strawberry Jam Advanced Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#6]

**Comment by niuez** [comment]
```
- level: StrawberryJam2021/3-Advanced
  maps:
    - sid: 'StrawberryJam2021/3-Advanced/astraxel'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/BlueXans'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Citrea'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/galaksyz'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Goldian'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/hennyburgr'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Indecx'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/JANisEXIST'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Jolly'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Julia'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Maladroit'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Meario'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/mmm'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/MousseMoose'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Nic'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Oppen'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/pugroy'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/RadleyMcTuneston'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Roborb'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/sp1029'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/TiltTheStars'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Tortoise'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Vamp'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Viv'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/Worldwaker2'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/3-Advanced/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
