### ISSUE TITLE
Strawberry Jam Expert Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#7]

**Comment by niuez** [comment]
```
- level: StrawberryJam2021/4-Expert
  maps:
    - sid: 'StrawberryJam2021/4-Expert/Agent'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/alicequasar'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Appels'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Archire'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Aspar'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Banana23'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Cabob'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/DanTKO'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Flamecrafter113'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/fonda1515'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/hivemindsrule'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/itsabrody'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Jackal'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/KAERRA'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/LethargicDoggo'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Linj'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Moladan'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/nyan'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/pansear'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/powerav'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/QuantumSpaceman'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/rdoggo8'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/RedBoule'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Scroogle'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Skunkynator'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/spirialis'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Stotch'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Vina'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/Yoshachobi7'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/4-Expert/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
