### ISSUE TITLE
Strawberry Jam Grandmaster Lobby

### ISSUE THREAD

**Issue by niuez** [niuez/celeste_data#8]

**Comment by niuez** [comment]
```
- level: StrawberryJam2021/5-Grandmaster
  maps:
    - sid: 'StrawberryJam2021/5-Grandmaster/alisticious'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/CaptainCarpensir'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Dav'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/DeathKontrol'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Ecl1psed'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/fishtank'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Hydro'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Linj'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/math'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/maya'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/RedBatNick'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Soloiini'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/tcookiem'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/tobyaaa'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/Todd'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/tofu'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/xlibiza'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/xplosives'
      name:
        en: ''
      sides: [0]
    - sid: 'StrawberryJam2021/5-Grandmaster/ZZ-HeartSide'
      name:
        en: ''
      sides: [0]
```
